version: "3.9"

x-env-common: &env_common
  CHROMA_HOST: ${CHROMA_HOST}
  PORT_CHROMA: ${PORT_CHROMA}
  CHROMA_URL: http://${CHROMA_HOST}:${PORT_CHROMA}
  PROJECT_DIR: ${PROJECT_DIR}
  PROJECT_PATH: ${PROJECT_PATH}
  CHROMA_DATA_DIR: ${CHROMA_DATA_DIR}
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  UI_MODE: ${UI_MODE}
  PORT_STREAMLIT: ${PORT_STREAMLIT}
  PORT_GRADIO: ${PORT_GRADIO}

services:
  chroma:
    # 0.5.1 → 0.4.24 へダウングレード
    image: ghcr.io/chroma-core/chroma:0.4.24
    container_name: chroma
    environment:
      IS_PERSISTENT: "TRUE"
    volumes:
      - chroma_data:${CHROMA_DATA_DIR}
    ports:
      - "${PORT_CHROMA}:${PORT_CHROMA}"

  app:
    build: ./app
    container_name: llc-app
    env_file: .env
    environment:
      <<: *env_common
    volumes:
      - ./app:/app
      - ${PROJECT_PATH}:${PROJECT_DIR}:ro
      - chroma_data:${CHROMA_DATA_DIR}
    depends_on:
      - chroma
    command: ["bash", "run.sh"]
    ports:
      - "${PORT_STREAMLIT}:${PORT_STREAMLIT}" # Streamlit
      - "${PORT_GRADIO}:${PORT_GRADIO}" # Gradio

volumes:
  chroma_data: