name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Syntax check (compileall)
        run: |
          cd app
          python -m compileall .

      - name: Docker Compose build
        run: docker compose -f docker-compose.yml build
